### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [AndriiTurko/homeworks_programming#1]
Тему написали чітко, але де решта. Як збираєтесь досліджувати інтернет в різних країнах? Зайти на сайт зі статистикою і там подивитися?

**Comment by AndriiTurko** [comment]
У мене ж є csv файл під назвою Users. Спочатку буду працювати з інформацією з цього файлу, якщо буде мало, то спробую знайти більше.

**Comment by anrom7** [comment]
Обов'язково треба думати що ще робити. Взяти дані з одного маленького csv і побудувати мапу це ми на лабораторній більше і складніше завдання вирішували.
